# Generated by Django 5.0.4 on 2024-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='post_name'),
            preserve_default=False,
        ),
    ]
