# Generated by Django 5.0.4 on 2024-06-04 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followers_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('kuzataman', 'user')},
        ),
        migrations.RemoveField(
            model_name='followers',
            name='kuzataman',
        ),
        migrations.AddField(
            model_name='followers',
            name='kuzataman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
